---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  roles:
   - role: tests/test_port
     vars:
       port: "8080"
   - role: tests/test_jenkins_login
     vars:
       port: "8080"
       
  tasks:

  - name: check artifactory port result 
    assert:
        that:
           - "{{ output_port.failed }} == false"    

  - name: check jenkins login work result 
    assert:
        that:
           - "'200' in output_jenkins_login_result.stdout"  


